feat: Add configurable wait attempts for AWS SSM command execution

diff --git a/aws-ssm-send-command/action.yml b/aws-ssm-send-command/action.yml
--- a/aws-ssm-send-command/action.yml
+++ b/aws-ssm-send-command/action.yml
@@ -13,6 +13,10 @@ inputs:
   command:
     required: true
     description: "The command to send"
+  wait_attempts:
+    required: false
+    description: "The number of attempts to wait for the command to be executed"
+    default: "10"
 outputs:
   command-id:
     description: "The ID of the command"
@@ -45,8 +49,36 @@ runs:
 
     - id: aws-ssm-wait-command-executed
       continue-on-error: true
-      shell: bash
-      run: aws ssm wait command-executed --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} --instance-id "${{ inputs.instance-id }}"
+      shell: bash --noprofile --norc -o pipefail {0}
+      run: |
+        for attempt in $(seq 1 ${{ inputs.wait_attempts }}); do
+
+          aws ssm wait command-executed --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} --instance-id "${{ inputs.instance-id }}"
+          exit_code=$?
+
+          if [ $exit_code -ne 0 ]; then
+            echo "Error: $exit_code"
+
+            if [ $attempt -eq ${{ inputs.wait_attempts }} ]; then
+              exit $exit_code
+            fi
+
+            status=$(aws ssm get-command-invocation \
+              --instance-id "${{ inputs.instance-id }}" \
+              --command-id ${{ fromJson(steps.aws-ssm-send-command.outputs.invocation).Command.CommandId }} \
+              --output json | jq -r '.Status')
+            echo "Status: $status"
+
+            if [ "$status" == "InProgress"  ] || [ "$status" == "Pending" ] || [ "$status" == "Delayed" ]; then
+              echo "Retrying in 10 seconds..."
+              sleep 10
+              echo
+              echo "Attempt $(($attempt + 1)) of ${{ inputs.wait_attempts }}"
+            else
+              exit 0
+            fi
+          fi
+        done
 
     - id: aws-ssm-get-command-invocation
       shell: bash
